// Movies Category Data
export const moviesData = {
    "name": "Movies",
    "icon": "🎬",
    "prompts": [
        {
            "challenge": "box_office_gross",
            "label": "Rank these movies by box office gross (highest to lowest)"
        },
        {
            "challenge": "production_budget",
            "label": "Rank these movies by production budget (highest to lowest)"
        },
        {
            "challenge": "runtime_minutes",
            "label": "Rank these movies by runtime (longest to shortest)"
        },
        {
            "challenge": "imdb_rating",
            "label": "Rank these movies by IMDb rating (highest to lowest)"
        },
        {
            "challenge": "rotten_tomatoes",
            "label": "Rank these movies by Rotten Tomatoes score (highest to lowest)"
        },
        {
            "challenge": "metacritic_score",
            "label": "Rank these movies by Metacritic score (highest to lowest)"
        },
        {
            "challenge": "release_year",
            "label": "Rank these movies by release year (newest to oldest)"
        },
        {
            "challenge": "opening_weekend",
            "label": "Rank these movies by opening weekend gross (highest to lowest)"
        },
        {
            "challenge": "international_gross",
            "label": "Rank these movies by international gross (highest to lowest)"
        },
        {
            "challenge": "oscar_nominations",
            "label": "Rank these movies by Oscar nominations (highest to lowest)"
        },
        {
            "challenge": "oscar_wins",
            "label": "Rank these movies by Oscar wins (highest to lowest)"
        },
        {
            "challenge": "screen_count",
            "label": "Rank these movies by number of screens (highest to lowest)"
        },
        {
            "challenge": "marketing_budget",
            "label": "Rank these movies by marketing budget (highest to lowest)"
        },
        {
            "challenge": "profit_margin",
            "label": "Rank these movies by profit margin (highest to lowest)"
        },
        {
            "challenge": "weeks_in_theaters",
            "label": "Rank these movies by weeks in theaters (highest to lowest)"
        },
        {
            "challenge": "dvd_sales",
            "label": "Rank these movies by DVD sales (highest to lowest)"
        },
        {
            "challenge": "streaming_views",
            "label": "Rank these movies by streaming views (highest to lowest)"
        },
        {
            "challenge": "social_media_mentions",
            "label": "Rank these movies by social media mentions (highest to lowest)"
        },
        {
            "challenge": "franchise_value",
            "label": "Rank these movies by franchise value (highest to lowest)"
        },
        {
            "challenge": "director_previous_hits",
            "label": "Rank these movies by director previous hits (highest to lowest)"
        },
        {
            "challenge": "star_power_rating",
            "label": "Rank these movies by star power rating (highest to lowest)"
        },
        {
            "challenge": "production_days",
            "label": "Rank these movies by production days (highest to lowest)"
        },
        {
            "challenge": "cgi_budget",
            "label": "Rank these movies by CGI budget (highest to lowest)"
        },
        {
            "challenge": "soundtrack_sales",
            "label": "Rank these movies by soundtrack sales (highest to lowest)"
        },
        {
            "challenge": "merchandising_revenue",
            "label": "Rank these movies by merchandising revenue (highest to lowest)"
        },
        {
            "challenge": "sequel_count",
            "label": "Rank these movies by number of sequels (highest to lowest)"
        },
        {
            "challenge": "remake_count",
            "label": "Rank these movies by number of remakes (highest to lowest)"
        },
        {
            "challenge": "cultural_impact_score",
            "label": "Rank these movies by cultural impact score (highest to lowest)"
        },
        {
            "challenge": "box_office_multiple",
            "label": "Rank these movies by box office multiple (highest to lowest)"
        },
        {
            "challenge": "award_ceremonies_count",
            "label": "Rank these movies by award ceremonies count (highest to lowest)"
        },
        {
            "challenge": "home_video_revenue",
            "label": "Rank these movies by home video revenue (highest to lowest)"
        },
        {
            "challenge": "international_markets",
            "label": "Rank these movies by international markets count (highest to lowest)"
        },
        {
            "challenge": "fan_rating_average",
            "label": "Rank these movies by fan rating average (highest to lowest)"
        }
    ],
    "items": {
        "001": {
            "name": "Aladdin (2019)",
            "code": "001",
            "box_office_gross": 1054.3,
            "production_budget": 183,
            "runtime_minutes": 128,
            "imdb_rating": 6.9,
            "rotten_tomatoes": 57,
            "metacritic_score": 53,
            "release_year": 2019,
            "opening_weekend": 91.5,
            "international_gross": 658.3,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4476,
            "marketing_budget": 85,
            "profit_margin": 386.3,
            "weeks_in_theaters": 21,
            "dvd_sales": 29.8,
            "streaming_views": 167.3,
            "social_media_mentions": 8.1,
            "franchise_value": 2.3,
            "director_previous_hits": 6,
            "star_power_rating": 8.1,
            "production_days": 98,
            "cgi_budget": 55,
            "soundtrack_sales": 4.5,
            "merchandising_revenue": 123.4,
            "sequel_count": 0,
            "remake_count": 1,
            "cultural_impact_score": 6.9,
            "box_office_multiple": 5.8,
            "award_ceremonies_count": 7,
            "home_video_revenue": 56.7,
            "international_markets": 87,
            "fan_rating_average": 7.3,
            "originalCode": "ALADDIN2019"
        },
        "002": {
            "name": "Alice in Wonderland (2010)",
            "code": "002",
            "box_office_gross": 1025.5,
            "production_budget": 200,
            "runtime_minutes": 108,
            "imdb_rating": 6.4,
            "rotten_tomatoes": 51,
            "metacritic_score": 53,
            "release_year": 2010,
            "opening_weekend": 116.1,
            "international_gross": 693.3,
            "oscar_nominations": 3,
            "oscar_wins": 2,
            "screen_count": 3728,
            "marketing_budget": 90,
            "profit_margin": 335.5,
            "weeks_in_theaters": 23,
            "dvd_sales": 48.9,
            "streaming_views": 145.6,
            "social_media_mentions": 3.8,
            "franchise_value": 2.7,
            "director_previous_hits": 12,
            "star_power_rating": 8.6,
            "production_days": 98,
            "cgi_budget": 85,
            "soundtrack_sales": 1.9,
            "merchandising_revenue": 234.5,
            "sequel_count": 1,
            "remake_count": 1,
            "cultural_impact_score": 7.2,
            "box_office_multiple": 5.1,
            "award_ceremonies_count": 18,
            "home_video_revenue": 89.4,
            "international_markets": 78,
            "fan_rating_average": 6.8,
            "originalCode": "ALICE2010"
        },
        "003": {
            "name": "Aquaman",
            "code": "003",
            "box_office_gross": 2299.1,
            "production_budget": 97,
            "runtime_minutes": 155,
            "imdb_rating": 8.8,
            "rotten_tomatoes": 65,
            "metacritic_score": 55,
            "release_year": 2018,
            "opening_weekend": 67.9,
            "international_gross": 816.4,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4125,
            "marketing_budget": 85,
            "profit_margin": 472,
            "weeks_in_theaters": 24,
            "dvd_sales": 22.4,
            "streaming_views": 145.6,
            "social_media_mentions": 4.8,
            "franchise_value": 2.1,
            "director_previous_hits": 2,
            "star_power_rating": 7.9,
            "production_days": 132,
            "cgi_budget": 75,
            "soundtrack_sales": 0.6,
            "merchandising_revenue": 98.7,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 6.8,
            "box_office_multiple": 7.2,
            "award_ceremonies_count": 5,
            "home_video_revenue": 48.9,
            "international_markets": 86,
            "fan_rating_average": 7.2,
            "originalCode": "AQUAMAN"
        },
        "004": {
            "name": "Avatar",
            "code": "004",
            "box_office_gross": 2923.7,
            "production_budget": 240,
            "runtime_minutes": 162,
            "imdb_rating": 8.2,
            "rotten_tomatoes": 82,
            "metacritic_score": 83,
            "release_year": 2009,
            "opening_weekend": 77,
            "international_gross": 2146,
            "oscar_nominations": 9,
            "oscar_wins": 3,
            "screen_count": 3461,
            "marketing_budget": 150,
            "profit_margin": 1135,
            "weeks_in_theaters": 34,
            "dvd_sales": 4,
            "streaming_views": 125.5,
            "social_media_mentions": 2.3,
            "franchise_value": 15.2,
            "director_previous_hits": 3,
            "star_power_rating": 8.5,
            "production_days": 497,
            "cgi_budget": 120,
            "soundtrack_sales": 1.2,
            "merchandising_revenue": 87.4,
            "sequel_count": 4,
            "remake_count": 0,
            "cultural_impact_score": 9.2,
            "box_office_multiple": 12.3,
            "award_ceremonies_count": 45,
            "home_video_revenue": 67.8,
            "international_markets": 98,
            "fan_rating_average": 8.1,
            "originalCode": "AVATAR"
        },
        "005": {
            "name": "Avengers: Endgame",
            "code": "005",
            "box_office_gross": 2798.5,
            "production_budget": 356,
            "runtime_minutes": 181,
            "imdb_rating": 8.5,
            "rotten_tomatoes": 94,
            "metacritic_score": 78,
            "release_year": 2019,
            "opening_weekend": 357.1,
            "international_gross": 1941,
            "oscar_nominations": 1,
            "oscar_wins": 0,
            "screen_count": 4662,
            "marketing_budget": 200,
            "profit_margin": 700.3,
            "weeks_in_theaters": 28,
            "dvd_sales": 2.1,
            "streaming_views": 234.6,
            "social_media_mentions": 8.9,
            "franchise_value": 25.3,
            "director_previous_hits": 4,
            "star_power_rating": 9.8,
            "production_days": 159,
            "cgi_budget": 200,
            "soundtrack_sales": 0.8,
            "merchandising_revenue": 456.7,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.9,
            "box_office_multiple": 7.9,
            "award_ceremonies_count": 23,
            "home_video_revenue": 89.4,
            "international_markets": 125,
            "fan_rating_average": 9.1,
            "originalCode": "AVENGERS_ENDGAME"
        },
        "006": {
            "name": "Avengers: Infinity War",
            "code": "006",
            "box_office_gross": 1373.2,
            "production_budget": 152,
            "runtime_minutes": 172,
            "imdb_rating": 8.2,
            "rotten_tomatoes": 85,
            "metacritic_score": 68,
            "release_year": 2018,
            "opening_weekend": 257.6,
            "international_gross": 1369.5,
            "oscar_nominations": 1,
            "oscar_wins": 0,
            "screen_count": 4474,
            "marketing_budget": 180,
            "profit_margin": 516.8,
            "weeks_in_theaters": 26,
            "dvd_sales": 1.8,
            "streaming_views": 201.3,
            "social_media_mentions": 7.2,
            "franchise_value": 23.8,
            "director_previous_hits": 3,
            "star_power_rating": 9.7,
            "production_days": 159,
            "cgi_budget": 180,
            "soundtrack_sales": 0.9,
            "merchandising_revenue": 387.2,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 8.6,
            "box_office_multiple": 6.4,
            "award_ceremonies_count": 18,
            "home_video_revenue": 76.3,
            "international_markets": 119,
            "fan_rating_average": 8.8,
            "originalCode": "AVENGERS_INFINITY_WAR"
        },
        "007": {
            "name": "Barbie",
            "code": "007",
            "box_office_gross": 1446.3,
            "production_budget": 145,
            "runtime_minutes": 114,
            "imdb_rating": 7,
            "rotten_tomatoes": 88,
            "metacritic_score": 80,
            "release_year": 2023,
            "opening_weekend": 162,
            "international_gross": 809.7,
            "oscar_nominations": 8,
            "oscar_wins": 1,
            "screen_count": 4178,
            "marketing_budget": 150,
            "profit_margin": 601.3,
            "weeks_in_theaters": 20,
            "dvd_sales": 8.2,
            "streaming_views": 134.5,
            "social_media_mentions": 28.9,
            "franchise_value": 5.2,
            "director_previous_hits": 2,
            "star_power_rating": 8.9,
            "production_days": 87,
            "cgi_budget": 35,
            "soundtrack_sales": 12.3,
            "merchandising_revenue": 567.8,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 9.4,
            "box_office_multiple": 10,
            "award_ceremonies_count": 32,
            "home_video_revenue": 45.6,
            "international_markets": 94,
            "fan_rating_average": 7.8,
            "originalCode": "BARBIE"
        },
        "008": {
            "name": "Beauty and the Beast (2017)",
            "code": "008",
            "box_office_gross": 1264.1,
            "production_budget": 160,
            "runtime_minutes": 129,
            "imdb_rating": 7.1,
            "rotten_tomatoes": 71,
            "metacritic_score": 65,
            "release_year": 2017,
            "opening_weekend": 174.8,
            "international_gross": 759.5,
            "oscar_nominations": 2,
            "oscar_wins": 0,
            "screen_count": 4210,
            "marketing_budget": 90,
            "profit_margin": 534.1,
            "weeks_in_theaters": 23,
            "dvd_sales": 38.4,
            "streaming_views": 198.7,
            "social_media_mentions": 9.2,
            "franchise_value": 2.8,
            "director_previous_hits": 4,
            "star_power_rating": 8.7,
            "production_days": 105,
            "cgi_budget": 45,
            "soundtrack_sales": 7.8,
            "merchandising_revenue": 345.6,
            "sequel_count": 0,
            "remake_count": 1,
            "cultural_impact_score": 7.9,
            "box_office_multiple": 7.9,
            "award_ceremonies_count": 22,
            "home_video_revenue": 89.4,
            "international_markets": 88,
            "fan_rating_average": 7.6,
            "originalCode": "BEAUTYANDTHEBEAST"
        },
        "009": {
            "name": "Black Panther",
            "code": "009",
            "box_office_gross": 1349.9,
            "production_budget": 200,
            "runtime_minutes": 134,
            "imdb_rating": 7.3,
            "rotten_tomatoes": 96,
            "metacritic_score": 88,
            "release_year": 2018,
            "opening_weekend": 202,
            "international_gross": 648.8,
            "oscar_nominations": 7,
            "oscar_wins": 3,
            "screen_count": 4020,
            "marketing_budget": 95,
            "profit_margin": 554.9,
            "weeks_in_theaters": 24,
            "dvd_sales": 24.5,
            "streaming_views": 189.4,
            "social_media_mentions": 15.7,
            "franchise_value": 3.8,
            "director_previous_hits": 3,
            "star_power_rating": 8.4,
            "production_days": 115,
            "cgi_budget": 80,
            "soundtrack_sales": 5.6,
            "merchandising_revenue": 123.4,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 9.8,
            "box_office_multiple": 6.7,
            "award_ceremonies_count": 45,
            "home_video_revenue": 67.8,
            "international_markets": 85,
            "fan_rating_average": 8.2,
            "originalCode": "BLACKPANTHER"
        },
        "010": {
            "name": "Captain America: Civil War",
            "code": "010",
            "box_office_gross": 1155,
            "production_budget": 250,
            "runtime_minutes": 147,
            "imdb_rating": 7.8,
            "rotten_tomatoes": 90,
            "metacritic_score": 75,
            "release_year": 2016,
            "opening_weekend": 179.1,
            "international_gross": 745.2,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4226,
            "marketing_budget": 105,
            "profit_margin": 400,
            "weeks_in_theaters": 20,
            "dvd_sales": 28.9,
            "streaming_views": 178.3,
            "social_media_mentions": 7.2,
            "franchise_value": 14.8,
            "director_previous_hits": 4,
            "star_power_rating": 8.8,
            "production_days": 148,
            "cgi_budget": 110,
            "soundtrack_sales": 0.8,
            "merchandising_revenue": 189.4,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.3,
            "box_office_multiple": 4.6,
            "award_ceremonies_count": 11,
            "home_video_revenue": 54.3,
            "international_markets": 83,
            "fan_rating_average": 8.1,
            "originalCode": "CAPTAINAMERICACIVILWAR"
        },
        "011": {
            "name": "The Dark Knight Rises",
            "code": "011",
            "box_office_gross": 1081.1,
            "production_budget": 250,
            "runtime_minutes": 165,
            "imdb_rating": 8.4,
            "rotten_tomatoes": 87,
            "metacritic_score": 78,
            "release_year": 2012,
            "opening_weekend": 160.9,
            "international_gross": 632.9,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4404,
            "marketing_budget": 100,
            "profit_margin": 331.1,
            "weeks_in_theaters": 23,
            "dvd_sales": 44.3,
            "streaming_views": 189.2,
            "social_media_mentions": 4.8,
            "franchise_value": 9.8,
            "director_previous_hits": 10,
            "star_power_rating": 9.1,
            "production_days": 167,
            "cgi_budget": 75,
            "soundtrack_sales": 4.2,
            "merchandising_revenue": 267.8,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.9,
            "box_office_multiple": 4.3,
            "award_ceremonies_count": 14,
            "home_video_revenue": 89.2,
            "international_markets": 80,
            "fan_rating_average": 8.6,
            "originalCode": "DARKKNIGHTRISES"
        },
        "012": {
            "name": "Deadpool",
            "code": "012",
            "box_office_gross": 783.1,
            "production_budget": 58,
            "runtime_minutes": 108,
            "imdb_rating": 8,
            "rotten_tomatoes": 85,
            "metacritic_score": 65,
            "release_year": 2016,
            "opening_weekend": 132.4,
            "international_gross": 420.4,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 3558,
            "marketing_budget": 45,
            "profit_margin": 622.1,
            "weeks_in_theaters": 16,
            "dvd_sales": 89.5,
            "streaming_views": 298.7,
            "social_media_mentions": 4.8,
            "franchise_value": 2.1,
            "director_previous_hits": 2,
            "star_power_rating": 8.3,
            "production_days": 58,
            "cgi_budget": 28,
            "soundtrack_sales": 3.2,
            "merchandising_revenue": 156.8,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 8.9,
            "box_office_multiple": 13.5,
            "award_ceremonies_count": 12,
            "home_video_revenue": 124.6,
            "international_markets": 62,
            "fan_rating_average": 8.2,
            "originalCode": "DEADPOOL"
        },
        "013": {
            "name": "Despicable Me 3",
            "code": "013",
            "box_office_gross": 1034.8,
            "production_budget": 80,
            "runtime_minutes": 90,
            "imdb_rating": 6.3,
            "rotten_tomatoes": 59,
            "metacritic_score": 49,
            "release_year": 2017,
            "opening_weekend": 72.4,
            "international_gross": 762.5,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4529,
            "marketing_budget": 65,
            "profit_margin": 474.8,
            "weeks_in_theaters": 23,
            "dvd_sales": 38.9,
            "streaming_views": 223.4,
            "social_media_mentions": 8.2,
            "franchise_value": 10.3,
            "director_previous_hits": 3,
            "star_power_rating": 7.4,
            "production_days": 82,
            "cgi_budget": 55,
            "soundtrack_sales": 2.1,
            "merchandising_revenue": 567.8,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 7.2,
            "box_office_multiple": 12.9,
            "award_ceremonies_count": 6,
            "home_video_revenue": 89.3,
            "international_markets": 89,
            "fan_rating_average": 6.8,
            "originalCode": "DESPICABLEME3"
        },
        "014": {
            "name": "Fast & Furious 6",
            "code": "014",
            "box_office_gross": 788.7,
            "production_budget": 160,
            "runtime_minutes": 130,
            "imdb_rating": 7,
            "rotten_tomatoes": 70,
            "metacritic_score": 61,
            "release_year": 2013,
            "opening_weekend": 97.4,
            "international_gross": 545.2,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 3771,
            "marketing_budget": 85,
            "profit_margin": 458.7,
            "weeks_in_theaters": 18,
            "dvd_sales": 67.3,
            "streaming_views": 234.8,
            "social_media_mentions": 3.2,
            "franchise_value": 7.8,
            "director_previous_hits": 8,
            "star_power_rating": 7.6,
            "production_days": 94,
            "cgi_budget": 45,
            "soundtrack_sales": 2.8,
            "merchandising_revenue": 98.4,
            "sequel_count": 3,
            "remake_count": 0,
            "cultural_impact_score": 7.4,
            "box_office_multiple": 4.9,
            "award_ceremonies_count": 8,
            "home_video_revenue": 89.2,
            "international_markets": 76,
            "fan_rating_average": 7.2,
            "originalCode": "FAST_FURIOUS_6"
        },
        "015": {
            "name": "Finding Dory",
            "code": "015",
            "box_office_gross": 1029.3,
            "production_budget": 200,
            "runtime_minutes": 97,
            "imdb_rating": 7.3,
            "rotten_tomatoes": 94,
            "metacritic_score": 77,
            "release_year": 2016,
            "opening_weekend": 135.1,
            "international_gross": 543.3,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4305,
            "marketing_budget": 90,
            "profit_margin": 339.3,
            "weeks_in_theaters": 24,
            "dvd_sales": 42.3,
            "streaming_views": 198.7,
            "social_media_mentions": 6.2,
            "franchise_value": 5.8,
            "director_previous_hits": 7,
            "star_power_rating": 7.9,
            "production_days": 134,
            "cgi_budget": 135,
            "soundtrack_sales": 1.8,
            "merchandising_revenue": 234.5,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 7.6,
            "box_office_multiple": 5.1,
            "award_ceremonies_count": 13,
            "home_video_revenue": 78.9,
            "international_markets": 82,
            "fan_rating_average": 7.7,
            "originalCode": "FINDINGDORY"
        },
        "016": {
            "name": "Frozen",
            "code": "016",
            "box_office_gross": 2209.5,
            "production_budget": 191,
            "runtime_minutes": 140,
            "imdb_rating": 6.7,
            "rotten_tomatoes": 90,
            "metacritic_score": 75,
            "release_year": 2013,
            "opening_weekend": 67.4,
            "international_gross": 880.1,
            "oscar_nominations": 2,
            "oscar_wins": 2,
            "screen_count": 3742,
            "marketing_budget": 85,
            "profit_margin": 549.5,
            "weeks_in_theaters": 34,
            "dvd_sales": 52.8,
            "streaming_views": 287.9,
            "social_media_mentions": 18.4,
            "franchise_value": 13.2,
            "director_previous_hits": 1,
            "star_power_rating": 7.8,
            "production_days": 92,
            "cgi_budget": 60,
            "soundtrack_sales": 14.7,
            "merchandising_revenue": 678.9,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 9.6,
            "box_office_multiple": 8.6,
            "award_ceremonies_count": 38,
            "home_video_revenue": 123.4,
            "international_markets": 90,
            "fan_rating_average": 8.3,
            "originalCode": "FROZEN"
        },
        "017": {
            "name": "Frozen 2",
            "code": "017",
            "box_office_gross": 1453.7,
            "production_budget": 150,
            "runtime_minutes": 103,
            "imdb_rating": 6.8,
            "rotten_tomatoes": 77,
            "metacritic_score": 64,
            "release_year": 2019,
            "opening_weekend": 130.3,
            "international_gross": 943.7,
            "oscar_nominations": 1,
            "oscar_wins": 0,
            "screen_count": 4440,
            "marketing_budget": 90,
            "profit_margin": 623.2,
            "weeks_in_theaters": 26,
            "dvd_sales": 34.7,
            "streaming_views": 245.6,
            "social_media_mentions": 12.4,
            "franchise_value": 13.2,
            "director_previous_hits": 1,
            "star_power_rating": 7.9,
            "production_days": 98,
            "cgi_budget": 65,
            "soundtrack_sales": 8.9,
            "merchandising_revenue": 489.2,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.7,
            "box_office_multiple": 9.7,
            "award_ceremonies_count": 15,
            "home_video_revenue": 87.3,
            "international_markets": 92,
            "fan_rating_average": 7.6,
            "originalCode": "FROZEN2"
        },
        "018": {
            "name": "Furious 7",
            "code": "018",
            "box_office_gross": 1515.3,
            "production_budget": 190,
            "runtime_minutes": 137,
            "imdb_rating": 7.1,
            "rotten_tomatoes": 81,
            "metacritic_score": 67,
            "release_year": 2015,
            "opening_weekend": 147.2,
            "international_gross": 1163.9,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4004,
            "marketing_budget": 85,
            "profit_margin": 589.8,
            "weeks_in_theaters": 22,
            "dvd_sales": 2.9,
            "streaming_views": 89.4,
            "social_media_mentions": 3.7,
            "franchise_value": 9.8,
            "director_previous_hits": 2,
            "star_power_rating": 8.2,
            "production_days": 112,
            "cgi_budget": 45,
            "soundtrack_sales": 1.8,
            "merchandising_revenue": 67.4,
            "sequel_count": 2,
            "remake_count": 0,
            "cultural_impact_score": 7.8,
            "box_office_multiple": 8,
            "award_ceremonies_count": 8,
            "home_video_revenue": 45.6,
            "international_markets": 89,
            "fan_rating_average": 7.9,
            "originalCode": "FURIOUS_7"
        },
        "019": {
            "name": "Guardians of the Galaxy",
            "code": "019",
            "box_office_gross": 773.3,
            "production_budget": 170,
            "runtime_minutes": 121,
            "imdb_rating": 8,
            "rotten_tomatoes": 92,
            "metacritic_score": 76,
            "release_year": 2014,
            "opening_weekend": 94.3,
            "international_gross": 440.2,
            "oscar_nominations": 2,
            "oscar_wins": 0,
            "screen_count": 4080,
            "marketing_budget": 75,
            "profit_margin": 448.3,
            "weeks_in_theaters": 20,
            "dvd_sales": 78.9,
            "streaming_views": 267.4,
            "social_media_mentions": 3.9,
            "franchise_value": 3.8,
            "director_previous_hits": 3,
            "star_power_rating": 7.8,
            "production_days": 85,
            "cgi_budget": 58,
            "soundtrack_sales": 4.5,
            "merchandising_revenue": 189.7,
            "sequel_count": 2,
            "remake_count": 0,
            "cultural_impact_score": 8.1,
            "box_office_multiple": 4.5,
            "award_ceremonies_count": 15,
            "home_video_revenue": 112.8,
            "international_markets": 68,
            "fan_rating_average": 8.3,
            "originalCode": "GUARDIANS_OF_THE_GALAXY"
        },
        "020": {
            "name": "The Hobbit: An Unexpected Journey",
            "code": "020",
            "box_office_gross": 1017,
            "production_budget": 180,
            "runtime_minutes": 169,
            "imdb_rating": 7.8,
            "rotten_tomatoes": 64,
            "metacritic_score": 58,
            "release_year": 2012,
            "opening_weekend": 84.6,
            "international_gross": 696.4,
            "oscar_nominations": 3,
            "oscar_wins": 0,
            "screen_count": 4045,
            "marketing_budget": 80,
            "profit_margin": 377,
            "weeks_in_theaters": 24,
            "dvd_sales": 56.7,
            "streaming_views": 167.8,
            "social_media_mentions": 4.2,
            "franchise_value": 8.9,
            "director_previous_hits": 8,
            "star_power_rating": 8.3,
            "production_days": 189,
            "cgi_budget": 100,
            "soundtrack_sales": 4.8,
            "merchandising_revenue": 234.5,
            "sequel_count": 2,
            "remake_count": 0,
            "cultural_impact_score": 8.1,
            "box_office_multiple": 5.7,
            "award_ceremonies_count": 16,
            "home_video_revenue": 98.7,
            "international_markets": 82,
            "fan_rating_average": 8,
            "originalCode": "HOBBITUNEXPECTED"
        },
        "021": {
            "name": "Incredibles 2",
            "code": "021",
            "box_office_gross": 1243.1,
            "production_budget": 200,
            "runtime_minutes": 118,
            "imdb_rating": 7.6,
            "rotten_tomatoes": 93,
            "metacritic_score": 80,
            "release_year": 2018,
            "opening_weekend": 182.7,
            "international_gross": 634.2,
            "oscar_nominations": 1,
            "oscar_wins": 0,
            "screen_count": 4410,
            "marketing_budget": 95,
            "profit_margin": 498.1,
            "weeks_in_theaters": 26,
            "dvd_sales": 29.7,
            "streaming_views": 178.4,
            "social_media_mentions": 6.8,
            "franchise_value": 4.5,
            "director_previous_hits": 8,
            "star_power_rating": 8.2,
            "production_days": 145,
            "cgi_budget": 120,
            "soundtrack_sales": 3.4,
            "merchandising_revenue": 234.5,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.2,
            "box_office_multiple": 6.2,
            "award_ceremonies_count": 19,
            "home_video_revenue": 78.9,
            "international_markets": 82,
            "fan_rating_average": 8,
            "originalCode": "INCREDIBLES2"
        },
        "022": {
            "name": "Iron Man 3",
            "code": "022",
            "box_office_gross": 1215.4,
            "production_budget": 200,
            "runtime_minutes": 130,
            "imdb_rating": 7.1,
            "rotten_tomatoes": 79,
            "metacritic_score": 62,
            "release_year": 2013,
            "opening_weekend": 174.1,
            "international_gross": 806.4,
            "oscar_nominations": 1,
            "oscar_wins": 0,
            "screen_count": 4253,
            "marketing_budget": 110,
            "profit_margin": 475.4,
            "weeks_in_theaters": 22,
            "dvd_sales": 32.1,
            "streaming_views": 156.8,
            "social_media_mentions": 5.9,
            "franchise_value": 12.4,
            "director_previous_hits": 5,
            "star_power_rating": 9.3,
            "production_days": 125,
            "cgi_budget": 95,
            "soundtrack_sales": 1.2,
            "merchandising_revenue": 245.6,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 7.4,
            "box_office_multiple": 6.1,
            "award_ceremonies_count": 14,
            "home_video_revenue": 67.8,
            "international_markets": 80,
            "fan_rating_average": 7.5,
            "originalCode": "IRONMAN3"
        },
        "023": {
            "name": "Joker",
            "code": "023",
            "box_office_gross": 1079,
            "production_budget": 55,
            "runtime_minutes": 122,
            "imdb_rating": 8.4,
            "rotten_tomatoes": 68,
            "metacritic_score": 59,
            "release_year": 2019,
            "opening_weekend": 96.2,
            "international_gross": 743.5,
            "oscar_nominations": 11,
            "oscar_wins": 2,
            "screen_count": 4374,
            "marketing_budget": 50,
            "profit_margin": 479,
            "weeks_in_theaters": 22,
            "dvd_sales": 19.8,
            "streaming_views": 156.7,
            "social_media_mentions": 12.9,
            "franchise_value": 1.8,
            "director_previous_hits": 3,
            "star_power_rating": 9,
            "production_days": 88,
            "cgi_budget": 15,
            "soundtrack_sales": 3.2,
            "merchandising_revenue": 34.5,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 9.1,
            "box_office_multiple": 19.6,
            "award_ceremonies_count": 48,
            "home_video_revenue": 45.2,
            "international_markets": 81,
            "fan_rating_average": 8.6,
            "originalCode": "JOKER"
        },
        "024": {
            "name": "Jurassic World Dominion",
            "code": "024",
            "box_office_gross": 1001.9,
            "production_budget": 185,
            "runtime_minutes": 147,
            "imdb_rating": 5.6,
            "rotten_tomatoes": 29,
            "metacritic_score": 38,
            "release_year": 2022,
            "opening_weekend": 145.1,
            "international_gross": 625.1,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4697,
            "marketing_budget": 100,
            "profit_margin": 286.9,
            "weeks_in_theaters": 18,
            "dvd_sales": 18.3,
            "streaming_views": 156.7,
            "social_media_mentions": 4.8,
            "franchise_value": 8.7,
            "director_previous_hits": 3,
            "star_power_rating": 8.1,
            "production_days": 134,
            "cgi_budget": 95,
            "soundtrack_sales": 0.9,
            "merchandising_revenue": 178.9,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 5.9,
            "box_office_multiple": 5.4,
            "award_ceremonies_count": 2,
            "home_video_revenue": 34.5,
            "international_markets": 88,
            "fan_rating_average": 5.8,
            "originalCode": "JURASSICWORLDDOMINION"
        },
        "025": {
            "name": "Jurassic World: Fallen Kingdom",
            "code": "025",
            "box_office_gross": 1310.5,
            "production_budget": 170,
            "runtime_minutes": 128,
            "imdb_rating": 6.1,
            "rotten_tomatoes": 47,
            "metacritic_score": 51,
            "release_year": 2018,
            "opening_weekend": 148,
            "international_gross": 892.7,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4485,
            "marketing_budget": 95,
            "profit_margin": 545.5,
            "weeks_in_theaters": 20,
            "dvd_sales": 26.7,
            "streaming_views": 189.3,
            "social_media_mentions": 5.4,
            "franchise_value": 8.7,
            "director_previous_hits": 4,
            "star_power_rating": 8.2,
            "production_days": 115,
            "cgi_budget": 85,
            "soundtrack_sales": 1.3,
            "merchandising_revenue": 234.5,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 6.7,
            "box_office_multiple": 7.7,
            "award_ceremonies_count": 4,
            "home_video_revenue": 56.7,
            "international_markets": 86,
            "fan_rating_average": 6.5,
            "originalCode": "JURASSICWORLDFALLEN"
        },
        "026": {
            "name": "Jurassic World",
            "code": "026",
            "box_office_gross": 1672.8,
            "production_budget": 150,
            "runtime_minutes": 124,
            "imdb_rating": 7,
            "rotten_tomatoes": 71,
            "metacritic_score": 59,
            "release_year": 2015,
            "opening_weekend": 208.8,
            "international_gross": 1019.4,
            "oscar_nominations": 1,
            "oscar_wins": 0,
            "screen_count": 4274,
            "marketing_budget": 100,
            "profit_margin": 711.4,
            "weeks_in_theaters": 29,
            "dvd_sales": 3.8,
            "streaming_views": 142.6,
            "social_media_mentions": 4.2,
            "franchise_value": 12.3,
            "director_previous_hits": 1,
            "star_power_rating": 7.8,
            "production_days": 78,
            "cgi_budget": 75,
            "soundtrack_sales": 0.4,
            "merchandising_revenue": 189.7,
            "sequel_count": 2,
            "remake_count": 0,
            "cultural_impact_score": 7.2,
            "box_office_multiple": 11.2,
            "award_ceremonies_count": 12,
            "home_video_revenue": 89.3,
            "international_markets": 95,
            "fan_rating_average": 7.5,
            "originalCode": "JURASSIC_WORLD"
        },
        "027": {
            "name": "Minions",
            "code": "027",
            "box_office_gross": 2356.9,
            "production_budget": 66,
            "runtime_minutes": 177,
            "imdb_rating": 8.1,
            "rotten_tomatoes": 56,
            "metacritic_score": 56,
            "release_year": 2015,
            "opening_weekend": 115.7,
            "international_gross": 822.8,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4311,
            "marketing_budget": 65,
            "profit_margin": 538.4,
            "weeks_in_theaters": 25,
            "dvd_sales": 45.2,
            "streaming_views": 234.5,
            "social_media_mentions": 14.3,
            "franchise_value": 10.3,
            "director_previous_hits": 2,
            "star_power_rating": 7.2,
            "production_days": 78,
            "cgi_budget": 50,
            "soundtrack_sales": 2.9,
            "merchandising_revenue": 789.3,
            "sequel_count": 2,
            "remake_count": 0,
            "cultural_impact_score": 8.1,
            "box_office_multiple": 15.6,
            "award_ceremonies_count": 8,
            "home_video_revenue": 98.7,
            "international_markets": 91,
            "fan_rating_average": 6.9,
            "originalCode": "MINIONS"
        },
        "028": {
            "name": "Pirates of the Caribbean: Dead Man's Chest",
            "code": "028",
            "box_office_gross": 1066.2,
            "production_budget": 225,
            "runtime_minutes": 151,
            "imdb_rating": 7.3,
            "rotten_tomatoes": 53,
            "metacritic_score": 53,
            "release_year": 2006,
            "opening_weekend": 135.6,
            "international_gross": 642.3,
            "oscar_nominations": 4,
            "oscar_wins": 1,
            "screen_count": 4133,
            "marketing_budget": 85,
            "profit_margin": 331.2,
            "weeks_in_theaters": 26,
            "dvd_sales": 78.9,
            "streaming_views": 189.4,
            "social_media_mentions": 2.1,
            "franchise_value": 15.3,
            "director_previous_hits": 3,
            "star_power_rating": 9.2,
            "production_days": 145,
            "cgi_budget": 95,
            "soundtrack_sales": 3.4,
            "merchandising_revenue": 345.6,
            "sequel_count": 3,
            "remake_count": 0,
            "cultural_impact_score": 7.8,
            "box_office_multiple": 4.7,
            "award_ceremonies_count": 21,
            "home_video_revenue": 134.5,
            "international_markets": 75,
            "fan_rating_average": 7.6,
            "originalCode": "PIRATESDEADMAN"
        },
        "029": {
            "name": "Rogue One: A Star Wars Story",
            "code": "029",
            "box_office_gross": 1058.7,
            "production_budget": 200,
            "runtime_minutes": 133,
            "imdb_rating": 7.8,
            "rotten_tomatoes": 84,
            "metacritic_score": 65,
            "release_year": 2016,
            "opening_weekend": 155.1,
            "international_gross": 532.2,
            "oscar_nominations": 2,
            "oscar_wins": 0,
            "screen_count": 4157,
            "marketing_budget": 95,
            "profit_margin": 363.7,
            "weeks_in_theaters": 22,
            "dvd_sales": 32.1,
            "streaming_views": 178.4,
            "social_media_mentions": 6.9,
            "franchise_value": 20.5,
            "director_previous_hits": 2,
            "star_power_rating": 7.8,
            "production_days": 145,
            "cgi_budget": 90,
            "soundtrack_sales": 2.8,
            "merchandising_revenue": 456.7,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.2,
            "box_office_multiple": 5.3,
            "award_ceremonies_count": 18,
            "home_video_revenue": 67.8,
            "international_markets": 84,
            "fan_rating_average": 8.1,
            "originalCode": "ROGUE1"
        },
        "030": {
            "name": "Skyfall",
            "code": "030",
            "box_office_gross": 1142.5,
            "production_budget": 200,
            "runtime_minutes": 143,
            "imdb_rating": 7.8,
            "rotten_tomatoes": 92,
            "metacritic_score": 81,
            "release_year": 2012,
            "opening_weekend": 88.4,
            "international_gross": 808.6,
            "oscar_nominations": 5,
            "oscar_wins": 2,
            "screen_count": 3505,
            "marketing_budget": 95,
            "profit_margin": 442.5,
            "weeks_in_theaters": 28,
            "dvd_sales": 41.7,
            "streaming_views": 123.4,
            "social_media_mentions": 3.2,
            "franchise_value": 8.7,
            "director_previous_hits": 7,
            "star_power_rating": 8.5,
            "production_days": 128,
            "cgi_budget": 45,
            "soundtrack_sales": 6.8,
            "merchandising_revenue": 67.3,
            "sequel_count": 2,
            "remake_count": 0,
            "cultural_impact_score": 8.6,
            "box_office_multiple": 5.7,
            "award_ceremonies_count": 36,
            "home_video_revenue": 78.4,
            "international_markets": 79,
            "fan_rating_average": 8.2,
            "originalCode": "SKYFALL"
        },
        "031": {
            "name": "Spider-Man: No Way Home",
            "code": "031",
            "box_office_gross": 1921.8,
            "production_budget": 200,
            "runtime_minutes": 148,
            "imdb_rating": 8.2,
            "rotten_tomatoes": 90,
            "metacritic_score": 71,
            "release_year": 2021,
            "opening_weekend": 260.1,
            "international_gross": 1001.4,
            "oscar_nominations": 1,
            "oscar_wins": 0,
            "screen_count": 4336,
            "marketing_budget": 120,
            "profit_margin": 880.3,
            "weeks_in_theaters": 24,
            "dvd_sales": 1.2,
            "streaming_views": 167.8,
            "social_media_mentions": 12.4,
            "franchise_value": 18.7,
            "director_previous_hits": 2,
            "star_power_rating": 9.1,
            "production_days": 105,
            "cgi_budget": 90,
            "soundtrack_sales": 0.6,
            "merchandising_revenue": 312.4,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.3,
            "box_office_multiple": 9.6,
            "award_ceremonies_count": 15,
            "home_video_revenue": 58.9,
            "international_markets": 103,
            "fan_rating_average": 8.9,
            "originalCode": "SPIDER_MAN_NO_WAY_HOME"
        },
        "032": {
            "name": "Star Wars: The Force Awakens",
            "code": "032",
            "box_office_gross": 2071.3,
            "production_budget": 245,
            "runtime_minutes": 138,
            "imdb_rating": 7.8,
            "rotten_tomatoes": 93,
            "metacritic_score": 80,
            "release_year": 2015,
            "opening_weekend": 247.9,
            "international_gross": 1131.6,
            "oscar_nominations": 5,
            "oscar_wins": 0,
            "screen_count": 4134,
            "marketing_budget": 150,
            "profit_margin": 743.8,
            "weeks_in_theaters": 32,
            "dvd_sales": 3.2,
            "streaming_views": 178.4,
            "social_media_mentions": 5.7,
            "franchise_value": 42.1,
            "director_previous_hits": 1,
            "star_power_rating": 8.9,
            "production_days": 132,
            "cgi_budget": 85,
            "soundtrack_sales": 2.1,
            "merchandising_revenue": 234.5,
            "sequel_count": 2,
            "remake_count": 0,
            "cultural_impact_score": 8.7,
            "box_office_multiple": 8.5,
            "award_ceremonies_count": 34,
            "home_video_revenue": 98.7,
            "international_markets": 112,
            "fan_rating_average": 8.3,
            "originalCode": "STAR_WARS_VII"
        },
        "033": {
            "name": "The Lion King (2019)",
            "code": "033",
            "box_office_gross": 1656.9,
            "production_budget": 260,
            "runtime_minutes": 118,
            "imdb_rating": 6.8,
            "rotten_tomatoes": 52,
            "metacritic_score": 55,
            "release_year": 2019,
            "opening_weekend": 191.8,
            "international_gross": 1419.2,
            "oscar_nominations": 1,
            "oscar_wins": 0,
            "screen_count": 4725,
            "marketing_budget": 140,
            "profit_margin": 596.9,
            "weeks_in_theaters": 26,
            "dvd_sales": 2.4,
            "streaming_views": 198.5,
            "social_media_mentions": 6.8,
            "franchise_value": 8.9,
            "director_previous_hits": 3,
            "star_power_rating": 8.7,
            "production_days": 95,
            "cgi_budget": 200,
            "soundtrack_sales": 4.2,
            "merchandising_revenue": 278.3,
            "sequel_count": 0,
            "remake_count": 1,
            "cultural_impact_score": 6.9,
            "box_office_multiple": 6.4,
            "award_ceremonies_count": 18,
            "home_video_revenue": 67.2,
            "international_markets": 108,
            "fan_rating_average": 6.5,
            "originalCode": "THE_LION_KING_2019"
        },
        "034": {
            "name": "Titanic",
            "code": "034",
            "box_office_gross": 2265.2,
            "production_budget": 200,
            "runtime_minutes": 194,
            "imdb_rating": 8,
            "rotten_tomatoes": 88,
            "metacritic_score": 75,
            "release_year": 1997,
            "opening_weekend": 28.6,
            "international_gross": 1528.1,
            "oscar_nominations": 14,
            "oscar_wins": 11,
            "screen_count": 2674,
            "marketing_budget": 75,
            "profit_margin": 1032.4,
            "weeks_in_theaters": 44,
            "dvd_sales": 8.5,
            "streaming_views": 89.2,
            "social_media_mentions": 1.8,
            "franchise_value": 3.2,
            "director_previous_hits": 2,
            "star_power_rating": 9.2,
            "production_days": 160,
            "cgi_budget": 18,
            "soundtrack_sales": 30,
            "merchandising_revenue": 15.6,
            "sequel_count": 0,
            "remake_count": 1,
            "cultural_impact_score": 9.8,
            "box_office_multiple": 11.3,
            "award_ceremonies_count": 67,
            "home_video_revenue": 134.2,
            "international_markets": 87,
            "fan_rating_average": 8.7,
            "originalCode": "TITANIC"
        },
        "035": {
            "name": "Top Gun: Maverick",
            "code": "035",
            "box_office_gross": 1495.7,
            "production_budget": 170,
            "runtime_minutes": 131,
            "imdb_rating": 8.3,
            "rotten_tomatoes": 96,
            "metacritic_score": 78,
            "release_year": 2022,
            "opening_weekend": 126.7,
            "international_gross": 776.8,
            "oscar_nominations": 6,
            "oscar_wins": 1,
            "screen_count": 4735,
            "marketing_budget": 100,
            "profit_margin": 645.2,
            "weeks_in_theaters": 31,
            "dvd_sales": 18.9,
            "streaming_views": 167.8,
            "social_media_mentions": 8.9,
            "franchise_value": 2.4,
            "director_previous_hits": 6,
            "star_power_rating": 9.1,
            "production_days": 134,
            "cgi_budget": 55,
            "soundtrack_sales": 2.4,
            "merchandising_revenue": 34.6,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.9,
            "box_office_multiple": 8.8,
            "award_ceremonies_count": 28,
            "home_video_revenue": 56.7,
            "international_markets": 78,
            "fan_rating_average": 8.6,
            "originalCode": "TOPGUNMAVERICK"
        },
        "036": {
            "name": "Toy Story 3",
            "code": "036",
            "box_office_gross": 1067.3,
            "production_budget": 200,
            "runtime_minutes": 103,
            "imdb_rating": 8.3,
            "rotten_tomatoes": 98,
            "metacritic_score": 92,
            "release_year": 2010,
            "opening_weekend": 110.3,
            "international_gross": 652,
            "oscar_nominations": 5,
            "oscar_wins": 2,
            "screen_count": 4028,
            "marketing_budget": 85,
            "profit_margin": 382.3,
            "weeks_in_theaters": 29,
            "dvd_sales": 58.9,
            "streaming_views": 234.5,
            "social_media_mentions": 5.4,
            "franchise_value": 12.6,
            "director_previous_hits": 9,
            "star_power_rating": 8.8,
            "production_days": 167,
            "cgi_budget": 145,
            "soundtrack_sales": 3.4,
            "merchandising_revenue": 567.8,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 9.3,
            "box_office_multiple": 5.3,
            "award_ceremonies_count": 42,
            "home_video_revenue": 123.4,
            "international_markets": 80,
            "fan_rating_average": 8.7,
            "originalCode": "TOYSTORY3"
        },
        "037": {
            "name": "Toy Story 4",
            "code": "037",
            "box_office_gross": 1073.8,
            "production_budget": 200,
            "runtime_minutes": 100,
            "imdb_rating": 7.7,
            "rotten_tomatoes": 97,
            "metacritic_score": 84,
            "release_year": 2019,
            "opening_weekend": 120.9,
            "international_gross": 642,
            "oscar_nominations": 2,
            "oscar_wins": 1,
            "screen_count": 4575,
            "marketing_budget": 100,
            "profit_margin": 373.8,
            "weeks_in_theaters": 25,
            "dvd_sales": 34.8,
            "streaming_views": 189.2,
            "social_media_mentions": 7.6,
            "franchise_value": 12.6,
            "director_previous_hits": 3,
            "star_power_rating": 8.4,
            "production_days": 156,
            "cgi_budget": 140,
            "soundtrack_sales": 2.1,
            "merchandising_revenue": 456.7,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.8,
            "box_office_multiple": 5.4,
            "award_ceremonies_count": 29,
            "home_video_revenue": 89.3,
            "international_markets": 84,
            "fan_rating_average": 8.1,
            "originalCode": "TOYSTORY4"
        },
        "038": {
            "name": "Transformers: Age of Extinction",
            "code": "038",
            "box_office_gross": 1104.1,
            "production_budget": 210,
            "runtime_minutes": 165,
            "imdb_rating": 5.6,
            "rotten_tomatoes": 18,
            "metacritic_score": 32,
            "release_year": 2014,
            "opening_weekend": 100,
            "international_gross": 845.2,
            "oscar_nominations": 0,
            "oscar_wins": 0,
            "screen_count": 4233,
            "marketing_budget": 95,
            "profit_margin": 399.1,
            "weeks_in_theaters": 19,
            "dvd_sales": 29.8,
            "streaming_views": 145.6,
            "social_media_mentions": 2.8,
            "franchise_value": 11.4,
            "director_previous_hits": 9,
            "star_power_rating": 7.7,
            "production_days": 178,
            "cgi_budget": 115,
            "soundtrack_sales": 1.2,
            "merchandising_revenue": 289.4,
            "sequel_count": 1,
            "remake_count": 0,
            "cultural_impact_score": 5.8,
            "box_office_multiple": 5.3,
            "award_ceremonies_count": 3,
            "home_video_revenue": 56.7,
            "international_markets": 85,
            "fan_rating_average": 5.9,
            "originalCode": "TRANSFORMERSAGE"
        },
        "039": {
            "name": "Transformers: Dark of the Moon",
            "code": "039",
            "box_office_gross": 1123.8,
            "production_budget": 195,
            "runtime_minutes": 154,
            "imdb_rating": 6.2,
            "rotten_tomatoes": 35,
            "metacritic_score": 42,
            "release_year": 2011,
            "opening_weekend": 97.9,
            "international_gross": 771.4,
            "oscar_nominations": 3,
            "oscar_wins": 0,
            "screen_count": 4088,
            "marketing_budget": 90,
            "profit_margin": 438.8,
            "weeks_in_theaters": 21,
            "dvd_sales": 45.6,
            "streaming_views": 167.8,
            "social_media_mentions": 3.2,
            "franchise_value": 11.4,
            "director_previous_hits": 8,
            "star_power_rating": 7.9,
            "production_days": 156,
            "cgi_budget": 105,
            "soundtrack_sales": 1.8,
            "merchandising_revenue": 345.6,
            "sequel_count": 2,
            "remake_count": 0,
            "cultural_impact_score": 6.4,
            "box_office_multiple": 5.8,
            "award_ceremonies_count": 7,
            "home_video_revenue": 78.9,
            "international_markets": 81,
            "fan_rating_average": 6.5,
            "originalCode": "TRANSFORMERSDARK"
        },
        "040": {
            "name": "Zootopia",
            "code": "040",
            "box_office_gross": 1025.5,
            "production_budget": 150,
            "runtime_minutes": 108,
            "imdb_rating": 8,
            "rotten_tomatoes": 98,
            "metacritic_score": 78,
            "release_year": 2016,
            "opening_weekend": 75.1,
            "international_gross": 693.3,
            "oscar_nominations": 1,
            "oscar_wins": 1,
            "screen_count": 3959,
            "marketing_budget": 75,
            "profit_margin": 400.5,
            "weeks_in_theaters": 27,
            "dvd_sales": 37.6,
            "streaming_views": 178.9,
            "social_media_mentions": 7.3,
            "franchise_value": 3.2,
            "director_previous_hits": 2,
            "star_power_rating": 7.6,
            "production_days": 112,
            "cgi_budget": 95,
            "soundtrack_sales": 2.3,
            "merchandising_revenue": 198.7,
            "sequel_count": 0,
            "remake_count": 0,
            "cultural_impact_score": 8.4,
            "box_office_multiple": 6.8,
            "award_ceremonies_count": 23,
            "home_video_revenue": 67.8,
            "international_markets": 85,
            "fan_rating_average": 8.3,
            "originalCode": "ZOOTOPIA"
        }
    }
};